In [2]:
import numpy as np
import pandas as pd
import rdkit 
from matplotlib import cm
from matplotlib import pyplot as plt
from rdkit.Chem import Descriptors

In [3]:
desc_list =Descriptors.descList
print(len(desc_list))

209

In [4]:
df = pd.read_csv('../../kampo_db/kampo_data_original/230922/check/kampo_ESI_tateishi_1004_checked.csv')
train = pd.read_csv('231202_tateishi_a-glucosidase_rdkit.csv')
all_variables =train.columns.values

smiles = df['smiles'].to_list()
mols = []
for i in smiles:
    mol = rdkit.Chem.MolFromSmiles(i)
    mols.append(mol)

df_mol = pd.DataFrame(mols)
df_mol.columns = ["ROMol"]
df_mol

                                                 ROMol
0     <rdkit.Chem.rdchem.Mol object at 0x7fb238461150>
1     <rdkit.Chem.rdchem.Mol object at 0x7fb2384611c0>
2     <rdkit.Chem.rdchem.Mol object at 0x7fb238461230>
3     <rdkit.Chem.rdchem.Mol object at 0x7fb2384612a0>
4     <rdkit.Chem.rdchem.Mol object at 0x7fb238461310>
...                                                ...
2644  <rdkit.Chem.rdchem.Mol object at 0x7fb2384b6030>
2645  <rdkit.Chem.rdchem.Mol object at 0x7fb2384b60a0>
2646  <rdkit.Chem.rdchem.Mol object at 0x7fb2384b6110>
2647  <rdkit.Chem.rdchem.Mol object at 0x7fb2384b6180>
2648  <rdkit.Chem.rdchem.Mol object at 0x7fb2384b61f0>

[2649 rows x 1 columns]

In [9]:
all_variables =train.columns.values[6:]
len(all_variables)

178

In [10]:
all_variables

array(['MaxAbsEStateIndex', 'MaxEStateIndex', 'MinAbsEStateIndex',
       'MinEStateIndex', 'qed', 'MolWt', 'HeavyAtomMolWt', 'ExactMolWt',
       'NumValenceElectrons', 'MaxPartialCharge', 'MinPartialCharge',
       'MaxAbsPartialCharge', 'MinAbsPartialCharge', 'FpDensityMorgan1',
       'FpDensityMorgan2', 'FpDensityMorgan3', 'BCUT2D_MWHI',
       'BCUT2D_MWLOW', 'BCUT2D_CHGHI', 'BCUT2D_CHGLO', 'BCUT2D_LOGPHI',
       'BCUT2D_LOGPLOW', 'BCUT2D_MRHI', 'BCUT2D_MRLOW', 'AvgIpc',
       'BalabanJ', 'BertzCT', 'Chi0', 'Chi0n', 'Chi0v', 'Chi1', 'Chi1n',
       'Chi1v', 'Chi2n', 'Chi2v', 'Chi3n', 'Chi3v', 'Chi4n', 'Chi4v',
       'HallKierAlpha', 'Ipc', 'Kappa1', 'Kappa2', 'Kappa3', 'LabuteASA',
       'PEOE_VSA1', 'PEOE_VSA10', 'PEOE_VSA11', 'PEOE_VSA12',
       'PEOE_VSA13', 'PEOE_VSA14', 'PEOE_VSA2', 'PEOE_VSA3', 'PEOE_VSA4',
       'PEOE_VSA5', 'PEOE_VSA6', 'PEOE_VSA7', 'PEOE_VSA8', 'PEOE_VSA9',
       'SMR_VSA1', 'SMR_VSA10', 'SMR_VSA2', 'SMR_VSA3', 'SMR_VSA4',
       'SMR_VSA5', 'SMR_VSA6', 'SMR_VSA7', 'SMR_VSA9', 'SlogP_VSA1',
       'SlogP_VSA10', 'SlogP_VSA11', 'SlogP_VSA12', 'SlogP_VSA2',
       'SlogP_VSA3', 'SlogP_VSA4', 'SlogP_VSA5', 'SlogP_VSA6',
       'SlogP_VSA7', 'SlogP_VSA8', 'TPSA', 'EState_VSA1', 'EState_VSA10',
       'EState_VSA11', 'EState_VSA2', 'EState_VSA3', 'EState_VSA4',
       'EState_VSA5', 'EState_VSA6', 'EState_VSA7', 'EState_VSA8',
       'EState_VSA9', 'VSA_EState1', 'VSA_EState10', 'VSA_EState2',
       'VSA_EState3', 'VSA_EState4', 'VSA_EState5', 'VSA_EState6',
       'VSA_EState7', 'VSA_EState8', 'VSA_EState9', 'FractionCSP3',
       'HeavyAtomCount', 'NHOHCount', 'NOCount',
       'NumAliphaticCarbocycles', 'NumAliphaticHeterocycles',
       'NumAliphaticRings', 'NumAromaticCarbocycles',
       'NumAromaticHeterocycles', 'NumAromaticRings', 'NumHAcceptors',
       'NumHDonors', 'NumHeteroatoms', 'NumRotatableBonds',
       'NumSaturatedCarbocycles', 'NumSaturatedHeterocycles',
       'NumSaturatedRings', 'RingCount', 'MolLogP', 'MolMR', 'fr_Al_COO',
       'fr_Al_OH', 'fr_Al_OH_noTert', 'fr_ArN', 'fr_Ar_N', 'fr_Ar_NH',
       'fr_Ar_OH', 'fr_COO', 'fr_COO2', 'fr_C_O', 'fr_C_O_noCOO',
       'fr_C_S', 'fr_Imine', 'fr_NH0', 'fr_NH1', 'fr_NH2',
       'fr_Ndealkylation1', 'fr_Ndealkylation2', 'fr_Nhpyrrole',
       'fr_aldehyde', 'fr_alkyl_halide', 'fr_allylic_oxid', 'fr_amide',
       'fr_amidine', 'fr_aniline', 'fr_aryl_methyl', 'fr_benzene',
       'fr_bicyclic', 'fr_ester', 'fr_ether', 'fr_furan', 'fr_guanido',
       'fr_halogen', 'fr_hdrzine', 'fr_hdrzone', 'fr_imidazole',
       'fr_imide', 'fr_ketone', 'fr_ketone_Topliss', 'fr_lactone',
       'fr_methoxy', 'fr_nitrile', 'fr_nitro', 'fr_nitro_arom',
       'fr_nitro_arom_nonortho', 'fr_para_hydroxylation', 'fr_phenol',
       'fr_phenol_noOrthoHbond', 'fr_piperdine', 'fr_piperzine',
       'fr_pyridine', 'fr_sulfide', 'fr_sulfonamd', 'fr_term_acetylene',
       'fr_thiazole', 'fr_thiophene', 'fr_unbrch_alkane'], dtype=object)

In [11]:
rdkit_desc = pd.DataFrame()
for i, j in Descriptors.descList:
    rdkit_desc[i] = df_mol["ROMol"].map(j)

/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)

/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)

/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)

/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)

/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)
/var/folders/qv/cp3ld5x909g1rq13yk4q7ybr0000gn/T/ipykernel_2753/1531612092.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  rdkit_desc[i] = df_mol["ROMol"].map(j)

In [12]:
rdkit_desc

,MaxAbsEStateIndex,MaxEStateIndex,MinAbsEStateIndex,MinEStateIndex,qed,MolWt,HeavyAtomMolWt,ExactMolWt,NumValenceElectrons,NumRadicalElectrons,...,fr_sulfide,fr_sulfonamd,fr_sulfone,fr_term_acetylene,fr_tetrazole,fr_thiazole,fr_thiocyan,fr_thiophene,fr_unbrch_alkane,fr_urea
0,4.354057,4.354057,0.654977,0.654977,0.516861,204.357,180.165,204.187801,84,0,...,0,0,0,0,0,0,0,0,0,0
1,10.456850,10.456850,0.056758,-1.511680,0.324816,422.386,400.210,422.121297,162,0,...,0,0,0,0,0,0,0,0,0,0
2,10.725440,10.725440,0.124815,-1.113079,0.652275,234.339,212.163,234.161980,94,0,...,0,0,0,0,0,0,0,0,0,0
3,2.633148,2.633148,0.762292,0.762292,0.606238,204.357,180.165,204.187801,84,0,...,0,0,0,0,0,0,0,0,0,0
4,10.180343,10.180343,0.142543,-0.933439,0.509593,290.271,276.159,290.079038,110,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2644,10.353249,10.353249,0.336705,-0.659494,0.234475,310.522,272.218,310.287180,130,0,...,0,0,0,0,0,0,0,0,12,0
2645,2.211806,2.211806,1.256944,1.256944,0.375859,98.189,84.077,98.109550,42,0,...,0,0,0,0,0,0,0,0,1,0
2646,8.241633,8.241633,0.274306,0.274306,0.530402,100.161,88.065,100.088815,42,0,...,0,0,0,0,0,0,0,0,0,0
2647,9.511204,9.511204,0.202060,-0.202060,0.526065,152.237,136.109,152.120115,62,0,...,0,0,0,0,0,0,0,0,0,0
2648,8.832813,8.832813,0.074327,0.074327,0.658919,219.248,206.144,219.112010,84,0,...,0,0,0,0,0,0,0,0,0,0

In [13]:
rdkit_desc_ =pd.concat([df[["number", "cid", "name", "smiles"]], rdkit_desc[all_variables]], axis=1)
rdkit_desc_

,number,cid,name,smiles,MaxAbsEStateIndex,MaxEStateIndex,MinAbsEStateIndex,MinEStateIndex,qed,MolWt,...,fr_phenol_noOrthoHbond,fr_piperdine,fr_piperzine,fr_pyridine,fr_sulfide,fr_sulfonamd,fr_term_acetylene,fr_thiazole,fr_thiophene,fr_unbrch_alkane
0,kampo_0002,11095734,(+)-Aromadendrene,CC1CCC2C1C3C(C3(C)C)CCC2=C,4.354057,4.354057,0.654977,0.654977,0.516861,204.357,...,0,0,0,0,0,0,0,0,0,0
1,kampo_0003,73533,(+)-Catechin 7-O-beta-D-xyloside,C1C(C(OC2=CC(=CC(=C21)O)OC3C(C(C(CO3)O)O)O)C4=...,10.456850,10.456850,0.056758,-1.511680,0.324816,422.386,...,3,0,0,0,0,0,0,0,0,0
2,kampo_0004,167812,(+)-Curcumenol,CC1CCC2C13CC(=C(C)C)C(O3)(C=C2C)O,10.725440,10.725440,0.124815,-1.113079,0.652275,234.339,...,0,0,0,0,0,0,0,0,0,0
3,kampo_0005,16212927,(+)-Cyclosativene,CC(C)C1CCC2(C3C1C4C2(C4C3)C)C,2.633148,2.633148,0.762292,0.762292,0.606238,204.357,...,0,0,0,0,0,0,0,0,0,0
4,kampo_0006,182232,(+)-Epicatechin,C1C(C(OC2=CC(=CC(=C21)O)O)C3=CC(=C(C=C3)O)O)O,10.180343,10.180343,0.142543,-0.933439,0.509593,290.271,...,4,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2644,kampo_2996,5282769,trans-11-Eicosenoic acid,CCCCCCCCC=CCCCCCCCCCC(=O)O,10.353249,10.353249,0.336705,-0.659494,0.234475,310.522,...,0,0,0,0,0,0,0,0,0,12
2645,kampo_2997,639662,trans-2-Heptene,CCCCC=CC,2.211806,2.211806,1.256944,1.256944,0.375859,98.189,...,0,0,0,0,0,0,0,0,0,1
2646,kampo_2998,5284503,trans-3-Hexen-1-ol,CCC=CCCO,8.241633,8.241633,0.274306,0.274306,0.530402,100.161,...,0,0,0,0,0,0,0,0,0,0
2647,kampo_3001,88302,trans-Pinocarveol,CC1(C2CC1C(=C)C(C2)O)C,9.511204,9.511204,0.202060,-0.202060,0.526065,152.237,...,0,0,0,0,0,0,0,0,0,0
2648,kampo_3002,449093,trans-Zeatin,CC(=CCNC1=NC=NC2=C1NC=N2)CO,8.832813,8.832813,0.074327,0.074327,0.658919,219.248,...,0,0,0,0,0,0,0,0,0,0

In [14]:
#rdkit_desc_.to_csv('231207_tateishi_kampo_rdkit.csv', index=False)